version: '3.8'
services:
  postgresql:
    image: "postgres"
    container_name: my-postgres
    environment:
      - POSTGRES_PASSWORD=your password 
    ports:
      - "5432:5432"
    volumes:
      - my-postgres-data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: backend22
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://postgres:<your password>@my-postgres:5432/postgres?schema=public

volumes:
  my-postgres-data:
